<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Nail IB | Privacy Policy</title>
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
  <link href="https://fonts.googleapis.com/css?family=Lato:100,100i,300,300i,400,400i,700,700i,900,900i&amp;subset=latin-ext" rel="stylesheet">
  <link href="https://fonts.googleapis.com/css?family=Raleway:100,100i,200,200i,300,300i,400,400i,500,500i,600,600i,700,700i,800,800i,900,900i&amp;subset=latin-ext" rel="stylesheet">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.5.0/css/font-awesome.min.css"/>
    <!-- RESET CSS -->
    <link rel="stylesheet" href="css/privacy_Reset.css" type="text/css" />
    <!-- STYLE SHEET -->
    <link rel="stylesheet" href="css/privacy_style.css" type="text/css" />
    <!-- WEBSITE ICON LINK-->
</head>

<body>

		<div class="wrap col-12">
        <div class="col-12">
            <div class="header container ">
                <div class="mobile-hide">
                    <div class="col-3 moble-col-3">
                        <div class="img-sec-logo">
                        <a href="index.php">
                            <img src="images/logo.svg">
                            </a>
                        </div>
                    </div>
                    <div class="col-9 moble-col-9">
                         <div class="menu-naviga">
                             <ul class="desktop-ul">
                                <li><a href="pricing.php">Pricing</a></li>
                                <li><a href="Subject.php">Subjects</a></li>
                                <li><a href="about.php"><span class="last-menu-butt">Login</span></a></li>
                             </ul>
                         </div>
                    </div>
                </div>
                <div class="mobile-show">
                    <div class="mobl-menue-col-9">
                         <p class="click-menu"><span class="nav-icon"><i class="fa fa-bars" aria-hidden="true"></i></span></p>
                         <ul class="desktop-ul-new">
                            <li><a href="pricing.php">Pricing</a></li>
                            <li><a href="Subject.php">Subject</a></li>
                            <li><a href="index.php">Register</a></li>
                            <li><a href="about.php">Login</a></li>
                         </ul>
                    </div>
                    <div class="mobl-menue-col-3">
                        <div class="img-sec-logo">
                        <a href="index.php">
                            <img src="images/logo.svg">
                            </a>
                        </div>
                    </div>
                </div>
				
            </div>
            <hr class="hrlinetop">
        </div>
        
        <!--end header-->
		

    <h1>Privacy Policy</h1>
    <p>
        We are obligated to protect the privacy of our visitors that is the students, parents and the educators who visit/ use our website for the services/products provided. Operating on global basis we require your personal data and information. However, we respect our customers and therefore we ensure that the personal data collected is used and disclosed professionally. By using our service, you agree that we can use the data in accordance to our privacy policy.
    </p>
    <h1>1) Collection Of Personal Data</h1> 
    <p>

        Personal Data is that piece of information which gives an identity to an individual. The type of personal data asked depends on what type service you shall use. It can include your name, e- mail address, telephone number and your credit card information, bank details, date of birth, educational records, exam results, etc. Reason for collecting the personal data: To provide educational content, to upload the assignment, to investigate the academic progress, to conduct surveys about the services and the feedbacks for the same.
    </p>
        <h1>2)  Third Parties, Disclosures </h1> 
    <p>


        The Nail IB will not share your personal data other than described in the privacy policy to the third parties. We will transfer your personal data to third- parties, who provide business- related service, client relationship management services, expense and payment process, on-line course providers, e- mail marketing service provider etc. Your personal data will not be sold, rented or otherwise be rented to third- party marketers.
    </p>
    <h1>3)  Cookies and Similar technologies</h1> 
    <p>
        A cookie is a piece of information in the form of a very small text file that is placed on an internet user’s hard drive. It is generated by a web page server that is normally created and operated by the host computer of the website. Cookies can be controlled from your browser’s preference settings to control all cookies saved locally to a visitor’s browser, no third party plug-ins are necessary. Various technologies are used to collect and store information when you visit our services. We allow trusted businesses to use cookies or similar technologies for advertising and research purposes on our services. The Nail IB uses a web analytics tool, Google Analytics, to monitor and evaluate site usage.
    </p>
    <h1>4) Transparency and Choice</h1> 
    <p>
        We understand that people have different privacy concerns. Our goal is to be clear about what information we collect, so that you can make meaningful choices about how it is used. We ensure that our users are protected from unauthorized access to or unauthorized alteration, disclosure or destruction of information that we hold.
    </p>
    <h1>5) Changes</h1> 
    <p>
        
        We reserve the right, at our discretion, to change, modify or add our privacy policy at any time and time to time. Any changes we may make to our privacy policy in the future will be posted on this page with an updated revision date. We will also keep prior versions of this Privacy Policy in an archive for your review.
    </p>
	
	<hr class="hrlinebootom">
		
  <div class="col-12">
	<div class="footer-nail">
            <div class="footer container">
                <div class="footer-sec">
                    <div class="col-3 footer-full-12">
                        <div class="footer-sec1 footer-sec1-1">
                            <div class="foter-lit">
                                <h4>Nail IB Inc.</h4>
                                <ul>
                                    <li><a href="Aboutus.php">About Us</a></li>
                                    <li><a href="privacy_policy.php">Privacy Policy</a></li>
                                    <li><a href="">Infringement Policies</a></li>
                                    <li><a href="why_us.php">Why Us</a></li>
                                    <li><a href="rules.php">Rules</a></li>

                                </ul>
                            </div>
                        </div>
                    </div>
                    <div class="col-3 footer-full-12">
                        <div class="footer-sec1 footer-sec1-2">
                            <div class="foter-lit">
                                <h4>Quick Links</h4>
                                <ul class="Quinklink">
                                    <li><a href="about.php">Login</a></li>
                                    <li><a href="Subject.php">Register Now</a></li>
                                    <li><a href="">List of subjects</a></li>
                                    <li><a href="">Coming up</a></li>
                                    <li><a href="">Prices</a></li>

                                </ul>
                            </div>
                        </div>
                    </div>
                    <div class="col-6 footer-full-12">
                        <div class="footer-sec1 footer-sec1-3">
                            <div class="foter-lit">
                                <h4>Language</h4>
                                <select class="langu-selec">
                                    <option>Hindi </option>
                                    <option>English</option>
                                    <option>Urdu</option>
                                </select>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        
        

        
        
    </div>
    
  
  </div>
	
	
    <!-- JQuery Attachment -->
	<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
    
        <script>
        $(document).ready(function(){
           $('.click-menu').click(function(){
               $(".desktop-ul-new").animate({
                    width: "toggle"
                });
           })
        });
        </script>
    <script type="text/javascript" src="jquery-3.1.1.min.js"></script>
    <script type="text/javascript" src="JS.js"></script>
</body>

</html>